name: Run tests

on:
  push:
  pull_request:

jobs:
  test:
    name: Run jest
    runs-on: ubuntu-latest
    steps:
      - name: "☁️ checkout repository"
        uses: actions/checkout@v3

      - name: "🔧 setup node"
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: "🔍 run tests"
        run: npm test
